version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: y18n
    versions:
    - 4.0.2
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: webpack-merge
    versions:
    - 5.7.3
  - dependency-name: xmldom
    versions:
    - 0.5.0
  - dependency-name: urijs
    versions:
    - 1.19.4
    - 1.19.6
  - dependency-name: sass-loader
    versions:
    - 10.1.1
