export default function (config) {
    config.set({
        basePath: '../..',
        frameworks: ['jasmine'],
        files: [
            {
                pattern: 'logo/conversejs-filled-192.png',
                watched: false,
                included: false,
                served: true,
                nocache: false,
            },
            {
                pattern: 'src/headless/dist/emoji.json',
                watched: false,
                included: false,
                served: true,
                type: 'json',
            },
            { pattern: 'src/headless/dist/*.js.map', included: false },
            { pattern: 'src/headless/dist/converse-headless.esm.js', type: 'module' },
            { pattern: 'src/headless/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/vcard/tests/update.js', type: 'module' },
            { pattern: 'src/headless/plugins/blocklist/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/bookmarks/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/caps/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/chat/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/disco/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/emoji/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/mam/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/muc/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/ping/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/pubsub/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/reactions/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/roster/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/smacks/tests/*.js', type: 'module' },
            { pattern: 'src/headless/plugins/status/tests/*.js', type: 'module' },
            { pattern: 'src/headless/shared/settings/tests/settings.js', type: 'module' },
        ],
        proxies: {
            '/dist/': '/base/src/headless/dist/',
        },
        client: {
            jasmine: {
                random: false,
            },
        },
        exclude: ['**/*.sw?'],
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['ChromeHeadless'],
        singleRun: false,
        concurrency: Infinity,
    });
}
