({
    baseUrl: "../",
    name: "almond",
    mainConfigFile: 'config.js',
    paths: {
        "backbone.vdomview":        "builds/backbone.vdomview",
        "converse-bookmarks":       "builds/converse-bookmarks",
        "converse-chatboxes":       "builds/converse-chatboxes",
        "converse-chatview":        "builds/converse-chatview",
        "converse-controlbox":      "builds/converse-controlbox",
        "converse-core":            "builds/converse-core",
        "converse-disco":           "builds/converse-disco",
        "converse-dragresize":      "builds/converse-dragresize",
        "converse-embedded":        "builds/converse-embedded",
        "converse-fullscreen":      "builds/converse-fullscreen",
        "converse-headline":        "builds/converse-headline",
        "converse-mam":             "builds/converse-mam",
        "converse-message-view":    "builds/converse-message-view",
        "converse-minimize":        "builds/converse-minimize",
        "converse-modal":           "builds/converse-modal",
        "converse-muc":             "builds/converse-muc",
        "converse-muc-views":       "builds/converse-muc-views",
        "converse-notification":    "builds/converse-notification",
        "converse-otr":             "builds/converse-otr",
        "converse-ping":            "builds/converse-ping",
        "converse-profile":         "builds/converse-profile",
        "converse-register":        "builds/converse-register",
        "converse-roomslist":       "builds/converse-roomslist",
        "converse-rosterview":      "builds/converse-rosterview",
        "converse-singleton":       "builds/converse-singleton",
        "converse-vcard":           "builds/converse-vcard",
        "form-utils":               "builds/utils/form",
        "i18n":                     "builds/i18n",
        "muc-utils":                "builds/utils/muc",
        "utils":                    "builds/utils/core"
    },
    wrap: {
        startFile: "start.frag",
        endFile: "end.frag"
    }
});
