define("converse-templates", [
    "tpl!src/templates/action",
    "tpl!src/templates/add_contact_dropdown",
    "tpl!src/templates/add_contact_form",
    "tpl!src/templates/change_status_message",
    "tpl!src/templates/chat_status",
    "tpl!src/templates/chatarea",
    "tpl!src/templates/chatbox",
    "tpl!src/templates/chatroom",
    "tpl!src/templates/chatrooms_tab",
    "tpl!src/templates/chats_panel",
    "tpl!src/templates/choose_status",
    "tpl!src/templates/contacts_panel",
    "tpl!src/templates/contacts_tab",
    "tpl!src/templates/controlbox",
    "tpl!src/templates/controlbox_toggle",
    "tpl!src/templates/field",
    "tpl!src/templates/form_checkbox",
    "tpl!src/templates/form_input",
    "tpl!src/templates/form_select",
    "tpl!src/templates/group_header",
    "tpl!src/templates/info",
    "tpl!src/templates/login_panel",
    "tpl!src/templates/login_tab",
    "tpl!src/templates/message",
    "tpl!src/templates/new_day",
    "tpl!src/templates/occupant",
    "tpl!src/templates/pending_contact",
    "tpl!src/templates/pending_contacts",
    "tpl!src/templates/requesting_contact",
    "tpl!src/templates/requesting_contacts",
    "tpl!src/templates/room_description",
    "tpl!src/templates/room_item",
    "tpl!src/templates/room_panel",
    "tpl!src/templates/roster",
    "tpl!src/templates/roster_item",
    "tpl!src/templates/select_option",
    "tpl!src/templates/status_option",
    "tpl!src/templates/toggle_chats",
    "tpl!src/templates/toolbar",
    "tpl!src/templates/trimmed_chat"
], function () {
    return {
        action:                 arguments[0],
        add_contact_dropdown:   arguments[1],
        add_contact_form:       arguments[2],
        change_status_message:  arguments[3],
        chat_status:            arguments[4],
        chatarea:               arguments[5],
        chatbox:                arguments[6],
        chatroom:               arguments[7],
        chatrooms_tab:          arguments[8],
        chats_panel:            arguments[9],
        choose_status:          arguments[10],
        contacts_panel:         arguments[11],
        contacts_tab:           arguments[12],
        controlbox:             arguments[13],
        controlbox_toggle:      arguments[14],
        field:                  arguments[15],
        form_checkbox:          arguments[16],
        form_input:             arguments[17],
        form_select:            arguments[18],
        group_header:           arguments[19],
        info:                   arguments[20],
        login_panel:            arguments[21],
        login_tab:              arguments[22],
        message:                arguments[23],
        new_day:                arguments[24],
        occupant:               arguments[25],
        pending_contact:        arguments[26],
        pending_contacts:       arguments[27],
        requesting_contact:     arguments[28],
        requesting_contacts:    arguments[29],
        room_description:       arguments[30],
        room_item:              arguments[31],
        room_panel:             arguments[32],
        roster:                 arguments[33],
        roster_item:            arguments[34],
        select_option:          arguments[35],
        status_option:          arguments[36],
        toggle_chats:           arguments[37],
        toolbar:                arguments[38],
        trimmed_chat:           arguments[39]
    };
});
