define("converse-templates", [
    "tpl!action",
    "tpl!add_contact_dropdown",
    "tpl!add_contact_form",
    "tpl!change_status_message",
    "tpl!chat_status",
    "tpl!chatarea",
    "tpl!chatbox",
    "tpl!chatroom",
    "tpl!chatrooms_tab",
    "tpl!chats_panel",
    "tpl!choose_status",
    "tpl!contacts_panel",
    "tpl!contacts_tab",
    "tpl!controlbox",
    "tpl!controlbox_toggle",
    "tpl!field",
    "tpl!form_checkbox",
    "tpl!form_input",
    "tpl!form_select",
    "tpl!group_header",
    "tpl!info",
    "tpl!login_panel",
    "tpl!login_tab",
    "tpl!message",
    "tpl!new_day",
    "tpl!occupant",
    "tpl!pending_contact",
    "tpl!pending_contacts",
    "tpl!requesting_contact",
    "tpl!requesting_contacts",
    "tpl!room_description",
    "tpl!room_item",
    "tpl!room_panel",
    "tpl!roster",
    "tpl!roster_item",
    "tpl!select_option",
    "tpl!search_contact",
    "tpl!status_option",
    "tpl!toggle_chats",
    "tpl!toolbar",
    "tpl!trimmed_chat"
], function () {
    return {
        action:                 arguments[0],
        add_contact_dropdown:   arguments[1],
        add_contact_form:       arguments[2],
        change_status_message:  arguments[3],
        chat_status:            arguments[4],
        chatarea:               arguments[5],
        chatbox:                arguments[6],
        chatroom:               arguments[7],
        chatrooms_tab:          arguments[8],
        chats_panel:            arguments[9],
        choose_status:          arguments[10],
        contacts_panel:         arguments[11],
        contacts_tab:           arguments[12],
        controlbox:             arguments[13],
        controlbox_toggle:      arguments[14],
        field:                  arguments[15],
        form_checkbox:          arguments[16],
        form_input:             arguments[17],
        form_select:            arguments[18],
        group_header:           arguments[19],
        info:                   arguments[20],
        login_panel:            arguments[21],
        login_tab:              arguments[22],
        message:                arguments[23],
        new_day:                arguments[24],
        occupant:               arguments[25],
        pending_contact:        arguments[26],
        pending_contacts:       arguments[27],
        requesting_contact:     arguments[28],
        requesting_contacts:    arguments[29],
        room_description:       arguments[30],
        room_item:              arguments[31],
        room_panel:             arguments[32],
        roster:                 arguments[33],
        roster_item:            arguments[34],
        select_option:          arguments[35],
        search_contact:         arguments[36],
        status_option:          arguments[37],
        toggle_chats:           arguments[38],
        toolbar:                arguments[39],
        trimmed_chat:           arguments[40]
    };
});
